# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0002_auto_20170322_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
